# Configuração de exemplo
# Copie para config.yaml e ajuste conforme necessário

environments:
  dev:
    s3_bucket: etl-dev-bucket
    redshift_cluster: dev-cluster
    
  prod:
    s3_bucket: etl-prod-bucket
    redshift_cluster: prod-cluster

data_sources:
  - name: source_1
    type: api
    endpoint: https://api.example.com/data
    
  - name: source_2
    type: database
    connection: postgres_default
